apiVersion: v1
kind: Service
metadata:
    labels:
      service: backend-user
    name: backend-user
spec:
    ports:
    - name: "8001"
      port: 8080
      targetPort: 8080
    selector:
      service: backend-user